# Generated by Django 5.2.5 on 2025-09-20 02:03

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", core.models.UserManager()),
            ],
        ),
    ]
